# Generated by Django 3.2.5 on 2021-08-18 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BlogAdmin', '0004_alter_blogmaster_createdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=50)),
                ('Emailid', models.EmailField(max_length=50)),
                ('Subject', models.CharField(max_length=80)),
                ('Comments', models.CharField(max_length=500)),
                ('Createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=50)),
                ('Emailid', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Mobile', models.IntegerField(max_length=50)),
                ('Createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.CharField(max_length=500)),
                ('Createdate', models.DateTimeField(auto_now_add=True)),
                ('BlogMaster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogAdmin.blogmaster')),
                ('RegisterMaster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.registermaster')),
            ],
        ),
    ]
