# Generated by Django 3.2.5 on 2021-08-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0004_alter_blogmaster_createdate'),
        ('Users', '0002_alter_registermaster_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emailid', models.EmailField(max_length=50)),
                ('Comments', models.CharField(max_length=500)),
                ('Createdate', models.DateTimeField(auto_now_add=True)),
                ('BlogMaster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogAdmin.blogmaster')),
            ],
        ),
        migrations.DeleteModel(
            name='BlogMaster',
        ),
        migrations.DeleteModel(
            name='RegisterMaster',
        ),
    ]
