# Generated by Django 3.2.5 on 2021-08-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20210819_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmaster',
            old_name='BlogMaster',
            new_name='Blogid',
        ),
    ]
