# Generated by Django 3.2.5 on 2021-08-19 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0004_alter_blogmaster_createdate'),
        ('Users', '0004_rename_blogmaster_commentmaster_blogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmaster',
            name='Blogid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='BlogAdmin.blogmaster'),
            preserve_default=False,
        ),
    ]
