# Generated by Django 3.2.5 on 2021-08-20 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_alter_commentmaster_blogid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMaster',
        ),
    ]
