# Generated by Django 3.2.5 on 2021-08-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_delete_contactmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=50)),
                ('Emailid', models.EmailField(max_length=50)),
                ('Subject', models.CharField(max_length=80)),
                ('Comments', models.CharField(max_length=500)),
                ('Createdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
