# Generated by Django 3.2.5 on 2021-08-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic', models.CharField(max_length=50, unique=True)),
                ('Category', models.CharField(max_length=50)),
                ('Intro', models.CharField(max_length=100, unique=True)),
                ('Description', models.CharField(max_length=800, unique=True)),
                ('Varified', models.BooleanField(default=False)),
                ('createdate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Regadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('createdate', models.DateTimeField()),
            ],
        ),
    ]
