# Generated by Django 3.2.5 on 2021-08-17 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyMaster',
            new_name='BlogMaster',
        ),
    ]
