# Generated by Django 3.2.5 on 2021-08-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogAdmin', '0002_rename_companymaster_blogmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmaster',
            name='Category',
            field=models.CharField(choices=[('Gaming', 'Gaming'), ('News', 'News'), ('Terrorisam', 'Terrorisam'), ('Country', 'Country'), ('Global-Issues', 'Global-Issues'), ('Social-Media', 'Social-Media')], default='Social-Media', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogmaster',
            name='Description',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='blogmaster',
            name='Intro',
            field=models.CharField(max_length=100),
        ),
    ]
